# source: https://raw.githubusercontent.com/rafguns/wosfile/master/wosfile/tags.py
# http://images.webofknowledge.com/WOKRS534DR1/help/WOS/hs_wos_fieldtags.html
# Format: (Abbreviation, Full label, Iterable?, One item per line?)
# - Abbreviation: WoS field tag
# - Full label: full label as provided by Thomson Reuters (or abbreviation if
#   not available)
# - Splittable: whether or not the field should be split into multiple items
# - One item per line: whether or not each item in an iterable field appears on
#   a new line in WoS plain text format
tags = (
    ('AB', 'Abstract', False, False),
    ('AF', 'Author Full Name', True, True),
    ('AR', 'Article Number', False, False),
    ('AU', 'Authors', True, True),
    ('BA', 'Book Authors', True, True),  # Correct?
    ('BE', 'Editors', True, True),
    ('BF', 'Book Authors Full Name', True, True),  # Correct?
    ('BN', 'International Standard Book Number (ISBN)', False, False),
    ('BP', 'Beginning Page', False, False),
    ('BS', 'Book Series Subtitle', False, False),
    ('C1', 'Author Address', False, True),  # Splitting of this field is handled separately
    ('C3', 'C3', True, False),  # this is presumably the author institution without address
    ('CA', 'Group Authors', False, False),
    ('CL', 'Conference Location', False, False),
    ('CR', 'Cited References', True, True),
    ('CT', 'Conference Title', False, False),
    ('CY', 'Conference Date', False, False),
    ('CL', 'Conference Location', False, False),
    ('DA', 'Date this report was generated', False, False),
    ('DE', 'Author Keywords', True, False),
    ('DI', 'Digital Object Identifier (DOI)', False, False),
    ('DT', 'Document Type', False, False),
    ('D2', 'Book Digital Object Identifier (DOI)', False, False),
    ('EA', 'Early access date', False, False),
    ('ED', 'Editors', False, False),
    ('EM', 'E-mail Address', True, False),
    ('EI', 'Electronic International Standard Serial Number (eISSN)', False, False),
    ('EP', 'Ending Page', False, False),
    ('EY', 'Early access year', False, False),
    ('FU', 'Funding Agency and Grant Number', False, False),
    ('FX', 'Funding Text', False, False),
    ('GA', 'Document Delivery Number', False, False),
    ('GP', 'Book Group Authors', False, False),
    ('HC', 'ESI Highly Cited Paper', False, False),
    ('HO', 'Conference Host', False, False),
    ('HP', 'ESI Hot Paper', False, False),
    ('ID', 'Keywords Plus', True, False),
    ('IS', 'Issue', False, False),
    ('J9', '29-Character Source Abbreviation', False, False),
    ('JI', 'ISO Source Abbreviation', False, False),
    ('LA', 'Language', False, False),
    ('MA', 'Meeting Abstract', False, False),
    ('NR', 'Cited Reference Count', False, False),
    ('OA', 'Open Access Indicator', False, False),
    ('OI', 'ORCID Identifier (Open Researcher and Contributor ID)', True, False),
    ('P2', 'Chapter count (Book Citation Index)', False, False),
    ('PA', 'Publisher Address', False, False),
    ('PD', 'Publication Date', False, False),
    ('PG', 'Page Count', False, False),
    ('PI', 'Publisher City', False, False),
    ('PM', 'PubMed ID', False, False),
    ('PN', 'Part Number', False, False),
    ('PT', 'Publication Type (J=Journal; B=Book; S=Series; P=Patent)', False, False),
    ('PU', 'Publisher', False, False),
    ('PY', 'Year Published', False, False),
    ('RI', 'ResearcherID Number', True, False),
    ('RP', 'Reprint Address', False, False),
    ('SC', 'Research Areas', True, False),
    ('SE', 'Book Series Title', False, False),
    ('SI', 'Special Issue', False, False),
    ('SN', 'International Standard Serial Number (ISSN)', False, False),
    ('SO', 'Publication Name', False, False),
    ('SP', 'Conference Sponsors', False, False),
    ('SU', 'Supplement', False, False),
    ('TC', 'Web of Science Core Collection Times Cited Count', False, False),
    ('TI', 'Document Title', False, False),
    ('U1', 'Usage Count (Last 180 Days)', False, False),
    ('U2', 'Usage Count (Since 2013)', False, False),
    ('UT', 'Unique Article Identifier', False, False),
    ('VL', 'Volume', False, False),
    ('WC', 'Web of Science Categories', True, False),
    ('WE', 'Web of Science indexes', True, False),
    ('Z9', 'Total Times Cited Count (WoS Core, BCI, and CSCD)', False, False),
    # From the WoS documentation
    ('A2', 'Other Abstract', False, False),
    ('AA', 'Additional Authors', False, False),
    ('AD', 'Application Details and Date', False, False),
    ('AE', 'Patent Assignee', False, False),
    ('AK', 'Abstract (Korean)', False, False),
    ('AN', 'Accession Number or PubMedID', False, False),
    ('AW', 'Item URL', False, False),
    ('BD', 'Broad Descriptors or Broad Terms', False, False),
    ('C2', 'Address (non-English)', False, False),
    ('CC', 'Concept Codes or CABI Codes', False, False),
    ('CE', 'Edition', False, False),
    ('CH', 'Chemicals & Biochemicals', False, False),
    ('CI', 'Derwent Compound Number', False, False),
    ('CN', 'CAS Registry Numbers; Commercial Names; Chemical', False, False),
    ('CO', 'CODEN', False, False),
    ('CP', 'Cited Patent(s)', False, False),
    ('DC', 'Derwent Class Code(s)', False, False),
    ('DF', 'Date Filed or Submitted', False, False),
    ('DL', 'DOI Link', False, False),
    ('DM', 'Demography', False, False),
    ('DN', 'DCR Number', False, False),
    ('DP', 'Discipline; Diseases', False, False),
    ('DS', 'Designated States', False, False),
    ('DY', 'Data Type', False, False),
    ('EC', 'Category', False, False),
    # ("EF", "End of File", False, False),
    # ("ER", "End of Record", False, False),
    ('FD', 'Further Application Details', False, False),
    ('FN', 'File Name', False, False),
    ('FP', 'Funding Name Preferred', False, False),
    ('FS', 'Field of Search', False, False),
    ('FT', 'Foreign Title', False, False),
    ('GE', 'Geographic Data', False, False),
    ('GI', 'Grant Information', False, False),
    ('GN', 'Gene Name', False, False),
    ('GS', 'Geospatial', False, False),
    ('GT', 'Time', False, False),
    ('IO', 'Issuing Organization', False, False),
    ('IP', 'International Patent Classification', False, False),
    ('IV', 'Investigators', False, False),
    ('JC', 'NLM Unique ID', False, False),
    ('LS', 'Language of Summary', False, False),
    ('LT', 'Literature Type', False, False),
    ('MC', 'Major Concepts or Derwent Manual Code(s)', False, False),
    ('ME', 'Medium', False, False),
    ('MH', 'MeSH Terms', False, False),
    ('MI', 'Miscellaneous Descriptors', False, False),
    ('MN', 'Markush Number', False, False),
    ('MQ', 'Methods & Equipment', False, False),
    ('NM', 'Personal Name Subject', False, False),
    ('NO', 'Comments, Corrections, Erratum', False, False),
    ('NP', 'Named Person', False, False),
    ('NT', 'Notes', False, False),
    ('OB', 'Record Owner', False, False),
    ('OC', 'Country of Original Patent Application Number', False, False),
    ('OD', 'Method', False, False),
    ('OP', 'Original Patent Application Number', False, False),
    ('OR', 'Organism Descriptors; Systematics', False, False),
    ('OS', 'Original Source', False, False),
    ('P1', 'Part Number', False, False),
    ('PC', 'Country of Patent', False, False),
    ('PE', 'Published Electronically', False, False),
    ('PR', 'Parts, Structures & Systems; Price', False, False),
    ('PS', 'Pages', False, False),
    ('PV', 'Place of Publication', False, False),
    ('RC', 'Date Created, Date Completed, Date Revised', False, False),
    ('RG', 'Derwent Registry Number', False, False),
    ('S1', 'Source Title (non-English)', False, False),
    ('SA', 'Status', False, False),
    ('SD', 'Molecular Sequence Data', False, False),
    ('SF', 'Space Flight Mission', False, False),
    ('SS', 'FSTA Section/Subsection; Citation Subset', False, False),
    ('ST', 'Super Taxa', False, False),
    ('TA', 'Taxonomic Data', False, False),
    ('TF', 'Technology Focus Abstract', False, False),
    ('TL', 'Country of Translation', False, False),
    ('TM', 'Geologic Time Data', False, False),
    ('TN', 'Taxa Notes', False, False),
    ('TR', 'Translators', False, False),
    ('TS', 'Translated Source', False, False),
    ('UC', 'Document Selection URL', False, False),
    ('UR', 'URL', False, False),
    ('VN', 'Version', False, False),
    ('VR', 'Version Number', False, False),
    ('WP', 'Publisher Web Address', False, False),
    ('X1', 'Article Title (non-English)', False, False),
    ('X2', 'Article Title (Transliterated)', False, False),
    ('X4', 'Spanish Abstract', False, False),
    ('X5', 'Spanish Author Keywords', False, False),
    ('Y1', 'Portuguese Document Title', False, False),
    ('Y4', 'Portuguese Abstract', False, False),
    ('Y5', 'Author Keywords (non-English); Portuguese Author Keywords', False, False),
    ('Z1', 'Article Title (Other Languages)', False, False),
    ('Z2', 'Authors (non-English)', False, False),
    ('Z3', 'Publication Name (Chinese)', False, False),
    ('Z4', 'Abstract (non-English)', False, False),
    ('Z5', 'Author Keywords (non-English)', False, False),
    ('Z6', 'Author Address (non-English)', False, False),
    ('Z7', 'E-mail Address (non-English)', False, False),
    ('Z8', 'CSCD Times Cited Count', False, False),
    ('ZK', 'Author Keywords (Korean)', False, False),
    # Undocumented tags
    ('ZS', 'Magic undocumented tag', False, False),
    ('ZB', 'Magic undocumented tag', False, False),
    ('ZR', 'Magic undocumented tag', False, False),
    ('ZA', 'Magic undocumented tag', False, False),
    ('ER', 'Magic undocumented tag', False, False),
    ('EF', 'Magic undocumented tag', False, False),
    ('G1', 'Magic undocumented tag', False, False),
    ('TO', 'Magic undocumented tag', False, False),
    ('D3', 'Magic undocumented tag', False, False),
)
is_splittable = {abbr: iterable for abbr, _, iterable, _ in tags}
has_item_per_line = {abbr: item_per_line for abbr, _, _, item_per_line in tags}

# Find new tags via
# -----------------
# from nacsos_data.util.academic.readers.wosfile.tags import tags
# import re
# TAG = re.compile(r"^[A-Z0-9]{2}")
# stags = []
# with open('/home/tim/Downloads/savedrecs.txt') as f:
#     for li, line in enumerate(f):
#         m = TAG.search(line)
#         if m:
#             stags.append(m[0])
# print(set(stags) - set([t[0] for t in tags]))
