"""Change BigInts to Strings for Twitter IDs

Revision ID: 2e7f4f4ccc1e
Revises: c2c8961a023a
Create Date: 2022-08-23 16:52:58.598469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7f4f4ccc1e'
down_revision = 'c2c8961a023a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_item', 'twitter_id', type_=sa.String, existing_type=sa.BigInteger)
    op.alter_column('twitter_item', 'twitter_author_id', type_=sa.String, existing_type=sa.BigInteger)
    op.alter_column('twitter_item', 'conversation_id', type_=sa.String, existing_type=sa.BigInteger)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_item', 'twitter_id', existing_type=sa.String, type_=sa.BigInteger)
    op.alter_column('twitter_item', 'twitter_author_id', existing_type=sa.String, type_=sa.BigInteger)
    op.alter_column('twitter_item', 'conversation_id', existing_type=sa.String, type_=sa.BigInteger)
    # ### end Alembic commands ###
