"""Set item.text nullable, and import.description non-nullable

Revision ID: 731be1ea0af7
Revises: f7ad0c0db0d9
Create Date: 2022-12-07 15:01:53.693070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731be1ea0af7'
down_revision = 'f7ad0c0db0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('import', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
