"""make twitter use bigint

Revision ID: 9a26a2b8ef0b
Revises: 3b7903c1882c
Create Date: 2022-05-30 19:38:34.121561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a26a2b8ef0b'
down_revision = '3b7903c1882c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_item', 'twitter_id', type_=sa.BigInteger, existing_type=sa.Integer)
    op.alter_column('twitter_item', 'twitter_author_id', type_=sa.BigInteger, existing_type=sa.Integer)
    op.alter_column('twitter_item', 'conversation_id', type_=sa.BigInteger, existing_type=sa.Integer)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitter_item', 'twitter_id', existing_type=sa.BigInteger, type_=sa.Integer)
    op.alter_column('twitter_item', 'twitter_author_id', existing_type=sa.BigInteger, type_=sa.Integer)
    op.alter_column('twitter_item', 'conversation_id', existing_type=sa.BigInteger, type_=sa.Integer)
    # ### end Alembic commands ###
