"""add import table

Revision ID: 9f5ab90ded04
Revises: 1148d434d975
Create Date: 2022-07-21 13:34:13.714813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f5ab90ded04'
down_revision = '1148d434d975'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('import',
                    sa.Column('import_id', postgresql.UUID(), nullable=False),
                    sa.Column('user_id', postgresql.UUID(), nullable=True),
                    sa.Column('project_id', postgresql.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('type', sa.Enum('ris', 'csv', 'jsonl', 'wos', 'scopus', 'ebsco', 'jstor', 'ovid', 'pop',
                                              'twitter', 'script', name='importtype'), nullable=False),
                    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=True),
                    sa.Column('time_started', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('time_finished', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
                    sa.PrimaryKeyConstraint('import_id'))
    op.create_index(op.f('ix_import_import_id'), 'import', ['import_id'], unique=True)
    op.create_index(op.f('ix_import_project_id'), 'import', ['project_id'], unique=False)
    op.create_index(op.f('ix_import_user_id'), 'import', ['user_id'], unique=False)

    op.create_table('m2m_import_item',
                    sa.Column('import_id', postgresql.UUID(), nullable=False),
                    sa.Column('item_id', postgresql.UUID(), nullable=False),
                    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=True),
                    sa.ForeignKeyConstraint(['import_id'], ['import.import_id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
                    sa.PrimaryKeyConstraint('import_id', 'item_id'))
    op.create_index(op.f('ix_m2m_import_item_import_id'), 'm2m_import_item', ['import_id'], unique=False)
    op.create_index(op.f('ix_m2m_import_item_item_id'), 'm2m_import_item', ['item_id'], unique=False)

    op.add_column('item', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'meta')

    op.drop_index(op.f('ix_m2m_import_item_item_id'), table_name='m2m_import_item')
    op.drop_index(op.f('ix_m2m_import_item_import_id'), table_name='m2m_import_item')
    op.drop_table('m2m_import_item')

    op.drop_index(op.f('ix_import_user_id'), table_name='import')
    op.drop_index(op.f('ix_import_project_id'), table_name='import')
    op.drop_index(op.f('ix_import_import_id'), table_name='import')
    op.drop_table('import')
    # ### end Alembic commands ###
