"""add twitter items

Revision ID: ad94859b7c75
Revises: 77b486e09680
Create Date: 2022-05-24 14:27:01.700609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad94859b7c75'
down_revision = '77b486e09680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_item',
                    sa.Column('item_id', postgresql.UUID(), nullable=False),
                    sa.Column('twitter_id', sa.Integer(), nullable=False),
                    sa.Column('twitter_author_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('language', sa.String(), nullable=True),
                    sa.Column('conversation_id', sa.Integer(), nullable=True),
                    sa.Column('referenced_tweets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('cashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('retweet_count', sa.Integer(), nullable=False),
                    sa.Column('reply_count', sa.Integer(), nullable=False),
                    sa.Column('like_count', sa.Integer(), nullable=False),
                    sa.Column('quote_count', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
                    sa.PrimaryKeyConstraint('item_id')
                    )
    op.create_index(op.f('ix_twitter_item_conversation_id'), 'twitter_item', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_twitter_item_item_id'), 'twitter_item', ['item_id'], unique=True)
    op.create_index(op.f('ix_twitter_item_twitter_author_id'), 'twitter_item', ['twitter_author_id'], unique=False)
    op.create_index(op.f('ix_twitter_item_twitter_id'), 'twitter_item', ['twitter_id'], unique=True)
    op.execute("CREATE TYPE projecttype AS ENUM('twitter', 'academic', 'patents')")
    op.add_column('project',
                  sa.Column('type', sa.Enum('twitter', 'academic', 'patents', name='projecttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'type')
    op.execute('DROP TYPE projecttype')
    op.drop_index(op.f('ix_twitter_item_twitter_id'), table_name='twitter_item')
    op.drop_index(op.f('ix_twitter_item_twitter_author_id'), table_name='twitter_item')
    op.drop_index(op.f('ix_twitter_item_item_id'), table_name='twitter_item')
    op.drop_index(op.f('ix_twitter_item_conversation_id'), table_name='twitter_item')
    op.drop_table('twitter_item')
    # ### end Alembic commands ###
