"""annotation task uniqueness constraint

Revision ID: c54713d59de5
Revises: 9a26a2b8ef0b
Create Date: 2022-05-31 18:04:35.492763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54713d59de5'
down_revision = '9a26a2b8ef0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('annotation_unique_assignment_id_key_repeat_tuple',
                                'annotation',
                                ['assignment_id', 'key', 'repeat'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_unique_assignment_id_key_repeat_tuple',
                       'annotation',
                       type_='unique')
    # ### end Alembic commands ###
