"""add rev to aiv

Revision ID: 10890590650e
Revises: cc7548db705c
Create Date: 2024-10-21 11:50:25.250846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10890590650e'
down_revision = 'cc7548db705c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_item_variant', sa.Column('import_revision', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_academic_item_variant_import_revision'), 'academic_item_variant', ['import_revision'], unique=False)
    op.drop_constraint('academic_item_variant_import_revision_id_fkey', 'academic_item_variant', type_='foreignkey')
    op.drop_column('academic_item_variant', 'import_revision_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_item_variant', sa.Column('import_revision_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('academic_item_variant_import_revision_id_fkey', 'academic_item_variant', 'import_revision', ['import_revision_id'], ['import_revision_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_academic_item_variant_import_revision'), table_name='academic_item_variant')
    op.drop_column('academic_item_variant', 'import_revision')
    # ### end Alembic commands ###
