"""uid to uname

Revision ID: 19e59a3a3aad
Revises: dc8ec86fa262
Create Date: 2024-02-09 21:50:14.344714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e59a3a3aad'
down_revision = 'dc8ec86fa262'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('TRUNCATE annotation_quality;')
    op.drop_constraint('annotation_quality_user_base_fkey', 'annotation_quality', type_='foreignkey')
    op.drop_constraint('annotation_quality_user_target_fkey', 'annotation_quality', type_='foreignkey')
    op.alter_column('annotation_quality', 'user_base',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('annotation_quality', 'user_target',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'annotation_quality', 'user', ['user_target'], ['username'], ondelete='CASCADE')
    op.create_foreign_key(None, 'annotation_quality', 'user', ['user_base'], ['username'], ondelete='CASCADE')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_quality', type_='foreignkey')
    op.drop_constraint(None, 'annotation_quality', type_='foreignkey')
    op.create_foreign_key('annotation_quality_user_target_fkey', 'annotation_quality', 'user', ['user_target'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('annotation_quality_user_base_fkey', 'annotation_quality', 'user', ['user_base'], ['user_id'], ondelete='CASCADE')
    op.alter_column('annotation_quality', 'user_target',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('annotation_quality', 'user_base',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
