"""drop highlgts

Revision ID: 31af32aff187
Revises: d4f577f16a2d
Create Date: 2024-10-18 15:35:00.130107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31af32aff187'
down_revision = 'd4f577f16a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_scope', 'highlighter_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_scope', sa.Column('highlighter_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
