"""bamid

Revision ID: 33c268ec1590
Revises: 19e59a3a3aad
Create Date: 2024-02-09 21:59:25.250228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c268ec1590'
down_revision = '19e59a3a3aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_quality', sa.Column('bot_annotation_metadata_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_annotation_quality_bot_annotation_metadata_id'), 'annotation_quality', ['bot_annotation_metadata_id'], unique=False)
    op.create_foreign_key(None, 'annotation_quality', 'bot_annotation_metadata', ['bot_annotation_metadata_id'], ['bot_annotation_metadata_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_quality', type_='foreignkey')
    op.drop_index(op.f('ix_annotation_quality_bot_annotation_metadata_id'), table_name='annotation_quality')
    op.drop_column('annotation_quality', 'bot_annotation_metadata_id')
    # ### end Alembic commands ###
