"""add item2project table

Revision ID: 3b7903c1882c
Revises: ad94859b7c75
Create Date: 2022-05-30 17:33:54.051456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b7903c1882c'
down_revision = 'ad94859b7c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m2m_project_item',
                    sa.Column('item_id', postgresql.UUID(), nullable=False),
                    sa.Column('project_id', postgresql.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
                    sa.PrimaryKeyConstraint('item_id', 'project_id')
                    )
    op.create_index(op.f('ix_m2m_project_item_item_id'), 'm2m_project_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_m2m_project_item_project_id'), 'm2m_project_item', ['project_id'], unique=False)
    op.add_column('twitter_item', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_item', 'status')
    op.drop_index(op.f('ix_m2m_project_item_project_id'), table_name='m2m_project_item')
    op.drop_index(op.f('ix_m2m_project_item_item_id'), table_name='m2m_project_item')
    op.drop_table('m2m_project_item')
    # ### end Alembic commands ###
