"""item edit flag

Revision ID: 8a29c3738b2e
Revises: 10890590650e
Create Date: 2024-10-22 10:44:27.031587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a29c3738b2e'
down_revision = '10890590650e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('time_edited', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'time_edited')
    # ### end Alembic commands ###
