"""add import mutex

Revision ID: ac3dc3438b8c
Revises: c5fc02b9d0bb
Create Date: 2024-10-16 22:24:28.001816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3dc3438b8c'
down_revision = 'c5fc02b9d0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('import_mutex', sa.Boolean(), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'import_mutex')
    # ### end Alembic commands ###
