"""tracker

Revision ID: b58d4f0b2b3c
Revises: 12ece8918eb8
Create Date: 2025-03-27 18:33:15.235540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b58d4f0b2b3c'
down_revision = '12ece8918eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_tracker', sa.Column('confidence_level', sa.Float(), server_default='0.9', nullable=False))
    op.add_column('annotation_tracker', sa.Column('bias', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('annotation_tracker', sa.Column('buscar_frontier', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_tracker', 'buscar_frontier')
    op.drop_column('annotation_tracker', 'bias')
    op.drop_column('annotation_tracker', 'confidence_level')
    # ### end Alembic commands ###
