"""add bots

Revision ID: f05e86f4be30
Revises: 2e7f4f4ccc1e
Create Date: 2022-10-24 18:32:54.898539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f05e86f4be30'
down_revision = '2e7f4f4ccc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_annotation_metadata',
    sa.Column('bot_annotation_metadata_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('CLASSIFICATION', 'RULES', 'TOPICS', 'CONSOLIDATE', 'SCRIPT', name='botkind'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('annotation_scope_id', sa.UUID(), nullable=True),
    sa.Column('annotation_scheme_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['annotation_scheme_id'], ['annotation_scheme.annotation_scheme_id'], ),
    sa.ForeignKeyConstraint(['annotation_scope_id'], ['assignment_scope.assignment_scope_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('bot_annotation_metadata_id')
    )
    op.create_index(op.f('ix_bot_annotation_metadata_annotation_scheme_id'), 'bot_annotation_metadata', ['annotation_scheme_id'], unique=False)
    op.create_index(op.f('ix_bot_annotation_metadata_annotation_scope_id'), 'bot_annotation_metadata', ['annotation_scope_id'], unique=False)
    op.create_index(op.f('ix_bot_annotation_metadata_bot_annotation_metadata_id'), 'bot_annotation_metadata', ['bot_annotation_metadata_id'], unique=True)
    op.create_index(op.f('ix_bot_annotation_metadata_project_id'), 'bot_annotation_metadata', ['project_id'], unique=False)
    op.create_table('bot_annotation',
    sa.Column('bot_annotation_id', sa.UUID(), nullable=False),
    sa.Column('bot_annotation_metadata_id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('repeat', sa.Integer(), nullable=False),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.Float(), nullable=True),
    sa.Column('value_str', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bot_annotation_metadata_id'], ['bot_annotation_metadata.bot_annotation_metadata_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
    sa.PrimaryKeyConstraint('bot_annotation_id'),
    sa.UniqueConstraint('bot_annotation_metadata_id', 'item_id', 'key', 'repeat')
    )
    op.create_index(op.f('ix_bot_annotation_bot_annotation_id'), 'bot_annotation', ['bot_annotation_id'], unique=True)
    op.create_index(op.f('ix_bot_annotation_bot_annotation_metadata_id'), 'bot_annotation', ['bot_annotation_metadata_id'], unique=False)
    op.create_index(op.f('ix_bot_annotation_item_id'), 'bot_annotation', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_annotation_item_id'), table_name='bot_annotation')
    op.drop_index(op.f('ix_bot_annotation_bot_annotation_metadata_id'), table_name='bot_annotation')
    op.drop_index(op.f('ix_bot_annotation_bot_annotation_id'), table_name='bot_annotation')
    op.drop_table('bot_annotation')
    op.drop_index(op.f('ix_bot_annotation_metadata_project_id'), table_name='bot_annotation_metadata')
    op.drop_index(op.f('ix_bot_annotation_metadata_bot_annotation_metadata_id'), table_name='bot_annotation_metadata')
    op.drop_index(op.f('ix_bot_annotation_metadata_annotation_scope_id'), table_name='bot_annotation_metadata')
    op.drop_index(op.f('ix_bot_annotation_metadata_annotation_scheme_id'), table_name='bot_annotation_metadata')
    op.drop_table('bot_annotation_metadata')
    # ### end Alembic commands ###
