"""drop user fk

Revision ID: f30a4bd3720d
Revises: e4ccac5bb802
Create Date: 2024-02-10 19:24:44.619608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30a4bd3720d'
down_revision = 'e4ccac5bb802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('annotation_quality_user_target_fkey', 'annotation_quality', type_='foreignkey')
    op.drop_constraint('annotation_quality_user_base_fkey', 'annotation_quality', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('annotation_quality_user_base_fkey', 'annotation_quality', 'user', ['user_base'], ['username'], ondelete='CASCADE')
    op.create_foreign_key('annotation_quality_user_target_fkey', 'annotation_quality', 'user', ['user_target'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###
