"""extend academic item

Revision ID: f7ad0c0db0d9
Revises: 71ed1752cdae
Create Date: 2022-11-28 19:01:04.674616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7ad0c0db0d9'
down_revision = '71ed1752cdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_item',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('wos_id', sa.String(), nullable=True),
    sa.Column('scopus_id', sa.String(), nullable=True),
    sa.Column('openalex_id', sa.String(), nullable=True),
    sa.Column('s2_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_slug', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_academic_item_doi'), 'academic_item', ['doi'], unique=False)
    op.create_index(op.f('ix_academic_item_keywords'), 'academic_item', ['keywords'], unique=False)
    op.create_index(op.f('ix_academic_item_openalex_id'), 'academic_item', ['openalex_id'], unique=False)
    op.create_index(op.f('ix_academic_item_publication_year'), 'academic_item', ['publication_year'], unique=False)
    op.create_index(op.f('ix_academic_item_s2_id'), 'academic_item', ['s2_id'], unique=False)
    op.create_index(op.f('ix_academic_item_scopus_id'), 'academic_item', ['scopus_id'], unique=False)
    op.create_index(op.f('ix_academic_item_source'), 'academic_item', ['source'], unique=False)
    op.create_index(op.f('ix_academic_item_title'), 'academic_item', ['title'], unique=False)
    op.create_index(op.f('ix_academic_item_title_slug'), 'academic_item', ['title_slug'], unique=False)
    op.create_index(op.f('ix_academic_item_wos_id'), 'academic_item', ['wos_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_item_wos_id'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_title_slug'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_title'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_source'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_scopus_id'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_s2_id'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_publication_year'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_openalex_id'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_keywords'), table_name='academic_item')
    op.drop_index(op.f('ix_academic_item_doi'), table_name='academic_item')
    op.drop_table('academic_item')
    # ### end Alembic commands ###
