"""new perm prio

Revision ID: fabb66a2156b
Revises: 8a29c3738b2e
Create Date: 2024-10-25 15:20:54.274056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabb66a2156b'
down_revision = '8a29c3738b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_permissions', sa.Column('annotations_prio', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_permissions', 'annotations_prio')
    # ### end Alembic commands ###
